{"level":"info","ts":"2025-02-13T15:33:54.344917083Z","msg":"Starting EDB Postgres for Kubernetes Instance Manager","logger":"instance-manager","logging_pod":"single-instance-cluster-1","version":"1.25.0","build":{"Version":"1.25.0","Commit":"6ce4b55ce","Date":"2024-12-23"}}
{"level":"info","ts":"2025-02-13T15:33:54.345062276Z","msg":"Checking for free disk space for WALs before starting PostgreSQL","logger":"instance-manager","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.386227403Z","msg":"starting tablespace manager","logger":"instance-manager","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.386513678Z","msg":"starting external server manager","logger":"instance-manager","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.386611244Z","msg":"starting controller-runtime manager","logger":"instance-manager","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.387314959Z","msg":"Starting EventSource","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","source":"kind source: *v1.Cluster"}
{"level":"info","ts":"2025-02-13T15:33:54.387485098Z","msg":"Starting Controller","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster"}
{"level":"info","ts":"2025-02-13T15:33:54.387723596Z","msg":"Starting EventSource","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-publication","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Publication","source":"kind source: *v1.Publication"}
{"level":"info","ts":"2025-02-13T15:33:54.387805964Z","msg":"Starting Controller","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-publication","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Publication"}
{"level":"info","ts":"2025-02-13T15:33:54.388555848Z","msg":"Starting EventSource","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-database","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Database","source":"kind source: *v1.Database"}
{"level":"info","ts":"2025-02-13T15:33:54.388575998Z","msg":"Starting Controller","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-database","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Database"}
{"level":"info","ts":"2025-02-13T15:33:54.394641092Z","msg":"Starting EventSource","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-subscription","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Subscription","source":"kind source: *v1.Subscription"}
{"level":"info","ts":"2025-02-13T15:33:54.394663966Z","msg":"Starting Controller","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-subscription","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Subscription"}
{"level":"info","ts":"2025-02-13T15:33:54.400158699Z","msg":"Starting webserver","logger":"instance-manager","logging_pod":"single-instance-cluster-1","address":":8000","hasTLS":true}
{"level":"info","ts":"2025-02-13T15:33:54.40050797Z","logger":"roles_reconciler","msg":"starting up the runnable","logger":"instance-manager","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.401008973Z","logger":"roles_reconciler","msg":"setting up RoleSynchronizer loop","logger":"instance-manager","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.401252698Z","msg":"Starting webserver","logger":"instance-manager","logging_pod":"single-instance-cluster-1","address":":9187","hasTLS":false}
{"level":"info","ts":"2025-02-13T15:33:54.401580586Z","msg":"Starting webserver","logger":"instance-manager","logging_pod":"single-instance-cluster-1","address":"localhost:8010","hasTLS":false}
{"level":"info","ts":"2025-02-13T15:33:54.403658472Z","msg":"Starting EventSource","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-external-server","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","source":"kind source: *v1.Cluster"}
{"level":"info","ts":"2025-02-13T15:33:54.403776651Z","msg":"Starting Controller","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-external-server","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster"}
{"level":"info","ts":"2025-02-13T15:33:54.404001614Z","msg":"Starting workers","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-external-server","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","worker count":1}
{"level":"info","ts":"2025-02-13T15:33:54.404230761Z","msg":"Starting EventSource","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-tablespaces","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","source":"kind source: *v1.Cluster"}
{"level":"info","ts":"2025-02-13T15:33:54.404308998Z","msg":"Starting Controller","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-tablespaces","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster"}
{"level":"info","ts":"2025-02-13T15:33:54.404468383Z","msg":"Starting workers","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-tablespaces","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","worker count":1}
{"level":"info","ts":"2025-02-13T15:33:54.485269017Z","msg":"Installed configuration file","logger":"instance-manager","logging_pod":"single-instance-cluster-1","pgdata":"/var/lib/postgresql/data/pgdata","filename":"pg_ident.conf"}
{"level":"info","ts":"2025-02-13T15:33:54.488025241Z","msg":"Starting workers","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-publication","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Publication","worker count":1}
{"level":"info","ts":"2025-02-13T15:33:54.488058444Z","msg":"Starting workers","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","worker count":1}
{"level":"info","ts":"2025-02-13T15:33:54.48911551Z","msg":"Starting workers","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-database","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Database","worker count":1}
{"level":"info","ts":"2025-02-13T15:33:54.496725925Z","msg":"Refreshed configuration file","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1","filename":"/controller/certificates/server.crt","secret":"single-instance-cluster-server"}
{"level":"info","ts":"2025-02-13T15:33:54.497374021Z","msg":"Refreshed configuration file","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1","filename":"/controller/certificates/server.key","secret":"single-instance-cluster-server"}
{"level":"info","ts":"2025-02-13T15:33:54.497733406Z","msg":"Starting workers","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-subscription","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Subscription","worker count":1}
{"level":"info","ts":"2025-02-13T15:33:54.500105076Z","msg":"Refreshed configuration file","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1","filename":"/controller/certificates/streaming_replica.crt","secret":"single-instance-cluster-replication"}
{"level":"info","ts":"2025-02-13T15:33:54.500939287Z","msg":"Refreshed configuration file","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1","filename":"/controller/certificates/streaming_replica.key","secret":"single-instance-cluster-replication"}
{"level":"info","ts":"2025-02-13T15:33:54.503186567Z","msg":"Refreshed configuration file","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1","filename":"/controller/certificates/client-ca.crt","secret":"single-instance-cluster-ca"}
{"level":"info","ts":"2025-02-13T15:33:54.505591738Z","msg":"Refreshed configuration file","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1","filename":"/controller/certificates/server-ca.crt","secret":"single-instance-cluster-ca"}
{"level":"info","ts":"2025-02-13T15:33:54.506830303Z","msg":"Installed configuration file","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1","pgdata":"/var/lib/postgresql/data/pgdata","filename":"pg_hba.conf"}
{"level":"info","ts":"2025-02-13T15:33:54.508492957Z","msg":"Installed configuration file","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1","pgdata":"/var/lib/postgresql/data/pgdata","filename":"custom.conf"}
{"level":"info","ts":"2025-02-13T15:33:54.508673173Z","msg":"Cluster status","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1","currentPrimary":"","targetPrimary":"single-instance-cluster-1","isReplicaCluster":false}
{"level":"info","ts":"2025-02-13T15:33:54.508756876Z","msg":"First primary instance bootstrap, marking myself as primary","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1","currentPrimary":"","targetPrimary":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.519301786Z","msg":"Extracting pg_controldata information","logger":"instance-manager","logging_pod":"single-instance-cluster-1","reason":"postmaster start up"}
{"level":"info","ts":"2025-02-13T15:33:54.526999871Z","logger":"pg_controldata","msg":"pg_control version number:            1700\nCatalog version number:               202406281\nDatabase system identifier:           7470927370578903059\nDatabase cluster state:               shut down\npg_control last modified:             Thu Feb 13 15:33:49 2025\nLatest checkpoint location:           0/2000028\nLatest checkpoint's REDO location:    0/2000028\nLatest checkpoint's REDO WAL file:    000000010000000000000002\nLatest checkpoint's TimeLineID:       1\nLatest checkpoint's PrevTimeLineID:   1\nLatest checkpoint's full_page_writes: on\nLatest checkpoint's NextXID:          0:740\nLatest checkpoint's NextOID:          16386\nLatest checkpoint's NextMultiXactId:  1\nLatest checkpoint's NextMultiOffset:  0\nLatest checkpoint's oldestXID:        730\nLatest checkpoint's oldestXID's DB:   1\nLatest checkpoint's oldestActiveXID:  0\nLatest checkpoint's oldestMultiXid:   1\nLatest checkpoint's oldestMulti's DB: 1\nLatest checkpoint's oldestCommitTsXid:0\nLatest checkpoint's newestCommitTsXid:0\nTime of latest checkpoint:            Thu Feb 13 15:33:49 2025\nFake LSN counter for unlogged rels:   0/3E8\nMinimum recovery ending location:     0/0\nMin recovery ending loc's timeline:   0\nBackup start location:                0/0\nBackup end location:                  0/0\nEnd-of-backup record required:        no\nwal_level setting:                    logical\nwal_log_hints setting:                on\nmax_connections setting:              100\nmax_worker_processes setting:         32\nmax_wal_senders setting:              10\nmax_prepared_xacts setting:           0\nmax_locks_per_xact setting:           64\ntrack_commit_timestamp setting:       off\nMaximum data alignment:               8\nDatabase block size:                  8192\nBlocks per segment of large relation: 131072\nWAL block size:                       8192\nBytes per WAL segment:                16777216\nMaximum length of identifiers:        64\nMaximum columns in an index:          32\nMaximum size of a TOAST chunk:        1996\nSize of a large-object chunk:         2048\nDate/time type storage:               64-bit integers\nFloat8 argument passing:              by value\nData page checksum version:           0\nMock authentication nonce:            b796ac0c36e9bcc7b22ba375ae87cc8eff021eb6124c66a141fec99de48597b8\n","pipe":"stdout","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.532419552Z","msg":"postmaster started","logger":"instance-manager","logging_pod":"single-instance-cluster-1","postMasterPID":23}
{"level":"info","ts":"2025-02-13T15:33:54.53450825Z","msg":"DB not available, will retry","logger":"instance-manager","logging_pod":"single-instance-cluster-1","err":"failed to connect to `user=postgres database=postgres`: /controller/run/.s.PGSQL.5432 (/controller/run): dial error: dial unix /controller/run/.s.PGSQL.5432: connect: no such file or directory"}
{"level":"info","ts":"2025-02-13T15:33:54.549603603Z","msg":"Instance is still down, will retry in 1 second","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f9cf8996-0988-40d0-9f72-1a13c0945e9d","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.585996459Z","msg":"Instance is still down, will retry in 1 second","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"b0a9c6c1-b9ea-4a67-a1bb-23396b51a5c3","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.598152628Z","logger":"postgres","msg":"2025-02-13 15:33:54.597 UTC [23] LOG:  redirecting log output to logging collector process","pipe":"stderr","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.59834695Z","logger":"postgres","msg":"2025-02-13 15:33:54.597 UTC [23] HINT:  Future log output will appear in directory \"/controller/log\".","pipe":"stderr","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.604052954Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:33:54.598 UTC","process_id":"23","session_id":"67ae10e2.17","session_line_num":"1","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"ending log output to stderr","hint":"Future log output will go to log destination \"csvlog\".","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:33:54.604425661Z","logger":"postgres","msg":"2025-02-13 15:33:54.598 UTC [23] LOG:  ending log output to stderr","source":"/controller/log/postgres","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.60453792Z","logger":"postgres","msg":"2025-02-13 15:33:54.598 UTC [23] HINT:  Future log output will go to log destination \"csvlog\".","source":"/controller/log/postgres","logging_pod":"single-instance-cluster-1"}
{"level":"info","ts":"2025-02-13T15:33:54.604633807Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:33:54.598 UTC","process_id":"23","session_id":"67ae10e2.17","session_line_num":"2","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"starting PostgreSQL 17.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22), 64-bit","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:33:54.604737856Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:33:54.598 UTC","process_id":"23","session_id":"67ae10e2.17","session_line_num":"3","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"listening on IPv4 address \"0.0.0.0\", port 5432","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:33:54.604817477Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:33:54.598 UTC","process_id":"23","session_id":"67ae10e2.17","session_line_num":"4","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"listening on IPv6 address \"::\", port 5432","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:33:54.604909319Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:33:54.600 UTC","process_id":"23","session_id":"67ae10e2.17","session_line_num":"5","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"listening on Unix socket \"/controller/run/.s.PGSQL.5432\"","backend_type":"postmaster","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:33:54.606646074Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:33:54.606 UTC","process_id":"29","session_id":"67ae10e2.1d","session_line_num":"1","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"database system was shut down at 2025-02-13 15:33:49 UTC","backend_type":"startup","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:33:54.62045322Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:33:54.620 UTC","process_id":"23","session_id":"67ae10e2.17","session_line_num":"6","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"database system is ready to accept connections","backend_type":"postmaster","query_id":"0"}}
{"level":"error","ts":"2025-02-13T15:33:55.037000204Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"e7ed2ee3-a58c-474d-b539-4ecac386dbfe","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:33:55.089004926Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"75e9e491-93a9-4e38-9f8f-f6d15c34db6e","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:33:55.141426277Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"0fdabd57-5827-45e1-b76e-39b2471e9c0a","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:33:55.237200514Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"6285f652-1ca9-4378-81de-5da544edad53","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:33:55.285463923Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"9f9f8111-78cb-4902-8d00-3ffbda307378","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:33:55.327209857Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"5cacc16c-265c-4275-922b-7030bf7f7239","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:33:55.436261646Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"772a1daf-4459-47af-9854-c8ee54eefa67","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:33:55.515566013Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"31d83266-14e0-443d-b45a-4428f5604be9","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:33:55.814133525Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"049be146-acfe-4ed4-a549-cd31b51da7e0","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:33:57.204615965Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"7cc5eb65-d352-4c41-a855-1baa06438d05","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:33:59.799744125Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"3052f07a-6440-4106-973f-54f18a1583c0","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:34:03.370854711Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"3ed553c2-2e98-42b1-b1aa-440108bf5f3f","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:34:03.452752131Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"59da853e-980c-465a-a89a-367c37da7657","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:34:03.499893606Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"9563c859-9199-4f46-b643-14cbaf460bbc","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:34:03.543643001Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"33a190f0-0317-4e46-8434-ffcc84472e25","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:34:03.587172747Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"f0b57cfb-0ec4-46c6-9405-7a713f1447d2","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:34:03.655159951Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"21ddc138-6113-4829-8ea8-b0b22871ab34","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:34:03.758373195Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"65fcac6c-2803-467f-8d1f-8051ef985f26","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:34:04.950692004Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"59a2247f-7823-4444-9466-f8ce1b71eb00","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"info","ts":"2025-02-13T15:34:45.810536941Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:34:45.809 UTC","user_name":"postgres","database_name":"postgres","process_id":"263","connection_from":"127.0.0.1:49056","session_id":"67ae1115.107","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:34:45 UTC","virtual_transaction_id":"99/4","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:34:45.824984575Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:34:45.824 UTC","user_name":"postgres","database_name":"postgres","process_id":"264","connection_from":"127.0.0.1:49060","session_id":"67ae1115.108","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:34:45 UTC","virtual_transaction_id":"0/5","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:35:50.950043402Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:35:50.947 UTC","user_name":"postgres","database_name":"postgres","process_id":"286","connection_from":"127.0.0.1:50354","session_id":"67ae1156.11e","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:35:50 UTC","virtual_transaction_id":"14/7","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:35:50.960686683Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:35:50.960 UTC","user_name":"postgres","database_name":"postgres","process_id":"287","connection_from":"127.0.0.1:50356","session_id":"67ae1156.11f","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:35:50 UTC","virtual_transaction_id":"15/7","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:37:24.934739827Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:37:24.934 UTC","user_name":"postgres","database_name":"postgres","process_id":"322","connection_from":"127.0.0.1:32814","session_id":"67ae11b4.142","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:37:24 UTC","virtual_transaction_id":"37/5","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:37:24.947289856Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:37:24.947 UTC","user_name":"postgres","database_name":"postgres","process_id":"323","connection_from":"127.0.0.1:32830","session_id":"67ae11b4.143","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:37:24 UTC","virtual_transaction_id":"36/6","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:38:54.703462783Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:38:54.703 UTC","process_id":"27","session_id":"67ae10e2.1b","session_line_num":"1","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"checkpoint starting: time","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:39:00.862851505Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:39:00.862 UTC","process_id":"27","session_id":"67ae10e2.1b","session_line_num":"2","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"checkpoint complete: wrote 64 buffers (0.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=6.154 s, sync=0.003 s, total=6.160 s; sync files=25, longest=0.002 s, average=0.001 s; distance=418 kB, estimate=418 kB; lsn=0/3000098, redo lsn=0/2068AE0","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:41:21.953297969Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:41:21.953 UTC","user_name":"postgres","database_name":"postgres","process_id":"405","connection_from":"127.0.0.1:34936","session_id":"67ae12a1.195","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:41:21 UTC","virtual_transaction_id":"84/6","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:41:21.964376413Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:41:21.964 UTC","user_name":"postgres","database_name":"postgres","process_id":"406","connection_from":"127.0.0.1:34940","session_id":"67ae12a1.196","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:41:21 UTC","virtual_transaction_id":"85/5","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:43:01.253453212Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:43:01.253 UTC","user_name":"postgres","database_name":"postgres","process_id":"441","connection_from":"127.0.0.1:58326","session_id":"67ae1305.1b9","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:43:01 UTC","virtual_transaction_id":"6/8","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:43:01.265349659Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:43:01.265 UTC","user_name":"postgres","database_name":"postgres","process_id":"442","connection_from":"127.0.0.1:58330","session_id":"67ae1305.1ba","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:43:01 UTC","virtual_transaction_id":"7/7","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"error","ts":"2025-02-13T15:50:44.979429566Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"5ffc6d60-e03a-490f-a6c8-07c0fc2092c9","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:56:06.691067166Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"cd3a5ee5-bd9a-4006-b42e-97d736cfda60","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:56:06.728363293Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"81712234-d7a4-4a9d-8d7a-fe8949f14750","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"info","ts":"2025-02-13T15:56:43.598479114Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:56:43.597 UTC","user_name":"postgres","database_name":"postgres","process_id":"751","connection_from":"127.0.0.1:56986","session_id":"67ae163b.2ef","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:56:43 UTC","virtual_transaction_id":"98/9","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:56:43.610490597Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:56:43.608 UTC","user_name":"postgres","database_name":"postgres","process_id":"752","connection_from":"127.0.0.1:56990","session_id":"67ae163b.2f0","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:56:43 UTC","virtual_transaction_id":"99/7","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:56:48.137311975Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:56:48.137 UTC","user_name":"postgres","database_name":"postgres","process_id":"753","connection_from":"127.0.0.1:58256","session_id":"67ae1640.2f1","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:56:48 UTC","virtual_transaction_id":"0/10","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:56:48.150549471Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:56:48.147 UTC","user_name":"postgres","database_name":"postgres","process_id":"754","connection_from":"127.0.0.1:58260","session_id":"67ae1640.2f2","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:56:48 UTC","virtual_transaction_id":"1/10","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"error","ts":"2025-02-13T15:58:36.37167564Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"5df4fa25-e86a-4ed3-8de9-986cb0fae173","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2025-02-13T15:58:36.411341303Z","msg":"Reconciler error","logger":"instance-manager","logging_pod":"single-instance-cluster-1","controller":"instance-cluster","controllerGroup":"postgresql.k8s.enterprisedb.io","controllerKind":"Cluster","Cluster":{"name":"single-instance-cluster","namespace":"postgresql-operator-system"},"namespace":"postgresql-operator-system","name":"single-instance-cluster","reconcileID":"828b5683-6407-4018-a1be-e9dfb7367f7e","error":"while updating database owner password: username key doesn't exist inside the secret","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224"}
{"level":"info","ts":"2025-02-13T15:58:49.782029049Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:58:49.781 UTC","user_name":"postgres","database_name":"postgres","process_id":"817","connection_from":"127.0.0.1:40856","session_id":"67ae16b9.331","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:58:49 UTC","virtual_transaction_id":"46/11","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:58:49.793792039Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:58:49.793 UTC","user_name":"postgres","database_name":"postgres","process_id":"818","connection_from":"127.0.0.1:40868","session_id":"67ae16b9.332","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:58:49 UTC","virtual_transaction_id":"47/9","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:58:54.197578353Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:58:54.197 UTC","user_name":"postgres","database_name":"postgres","process_id":"822","connection_from":"127.0.0.1:40874","session_id":"67ae16be.336","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:58:54 UTC","virtual_transaction_id":"50/11","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T15:58:54.211106637Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 15:58:54.210 UTC","user_name":"postgres","database_name":"postgres","process_id":"823","connection_from":"127.0.0.1:40886","session_id":"67ae16be.337","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 15:58:54 UTC","virtual_transaction_id":"51/9","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T16:05:47.213263657Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 16:05:47.213 UTC","user_name":"postgres","database_name":"postgres","process_id":"990","connection_from":"127.0.0.1:43862","session_id":"67ae185b.3de","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 16:05:47 UTC","virtual_transaction_id":"61/10","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T16:05:47.225096709Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 16:05:47.224 UTC","user_name":"postgres","database_name":"postgres","process_id":"991","connection_from":"127.0.0.1:43870","session_id":"67ae185b.3df","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 16:05:47 UTC","virtual_transaction_id":"62/15","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T16:05:51.724336956Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 16:05:51.724 UTC","user_name":"postgres","database_name":"postgres","process_id":"992","connection_from":"127.0.0.1:43886","session_id":"67ae185f.3e0","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 16:05:51 UTC","virtual_transaction_id":"63/11","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T16:05:51.736444582Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 16:05:51.736 UTC","user_name":"postgres","database_name":"postgres","process_id":"993","connection_from":"127.0.0.1:43890","session_id":"67ae185f.3e1","session_line_num":"1","command_tag":"authentication","session_start_time":"2025-02-13 16:05:51 UTC","virtual_transaction_id":"64/15","transaction_id":"0","error_severity":"FATAL","sql_state_code":"28P01","message":"password authentication failed for user \"postgres\"","detail":"User \"postgres\" has no password assigned.\nConnection matched file \"/var/lib/postgresql/data/pgdata/pg_hba.conf\" line 25: \"host all all all scram-sha-256\"","backend_type":"client backend","query_id":"0"}}
{"level":"info","ts":"2025-02-13T16:08:54.606703987Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 16:08:54.606 UTC","process_id":"27","session_id":"67ae10e2.1b","session_line_num":"3","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"checkpoint starting: time","backend_type":"checkpointer","query_id":"0"}}
{"level":"info","ts":"2025-02-13T16:08:54.712155495Z","logger":"postgres","msg":"record","logging_pod":"single-instance-cluster-1","record":{"log_time":"2025-02-13 16:08:54.712 UTC","process_id":"27","session_id":"67ae10e2.1b","session_line_num":"4","session_start_time":"2025-02-13 15:33:54 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.102 s, sync=0.002 s, total=0.107 s; sync files=2, longest=0.001 s, average=0.001 s; distance=32352 kB, estimate=32352 kB; lsn=0/4000BD0, redo lsn=0/4000B78","backend_type":"checkpointer","query_id":"0"}}
